# Generated by Django 3.2.10 on 2023-12-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
