# Generated by Django 3.2.10 on 2023-12-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20231220_1702'),
        ('game', '0002_auto_20231220_1836'),
    ]

    operations = [
    ]
