# Generated by Django 3.2.10 on 2023-12-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_match_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.IntegerField(),
        ),
    ]
