# Generated by Django 3.2.10 on 2023-12-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20231230_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_winner',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
