# Generated by Django 4.2.7 on 2023-11-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('online', models.BooleanField()),
                ('id42', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
            ],
        ),
    ]
