# Generated by Django 3.2.10 on 2023-12-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usermine_jwt'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermine',
            name='totp',
            field=models.CharField(default='', max_length=255),
        ),
    ]
