# Generated by Django 3.2.10 on 2023-11-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usermine_jwt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermine',
            name='jwt',
            field=models.CharField(default='', max_length=255),
        ),
    ]
