# Generated by Django 3.2.10 on 2023-12-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20231210_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermine',
            name='mail2FACode',
            field=models.CharField(default=-1, max_length=6),
        ),
    ]
