# Generated by Django 3.2.10 on 2023-12-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usermine_mail2facode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermine',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='password'),
        ),
    ]
