# Generated by Django 3.2.10 on 2023-12-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usermine_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermine',
            name='mail2FACode_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
