# Generated by Django 3.2.10 on 2023-12-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usermine_mail2facode_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermine',
            name='validated2FA',
            field=models.BooleanField(default=False),
        ),
    ]
