# Generated by Django 3.2.10 on 2023-12-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_usermine_matches_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermine',
            name='matches_played',
        ),
    ]
