# Generated by Django 3.2.10 on 2024-01-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_usermine_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermine',
            name='avatar',
            field=models.CharField(default='default.png', max_length=128, unique=True),
        ),
    ]
