# Generated by Django 3.2.10 on 2024-01-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_usermine_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermine',
            name='avatar',
            field=models.CharField(default='media/avatars/Pingu_default.png', max_length=128, unique=True),
        ),
    ]
