# Generated by Django 3.2.10 on 2024-01-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_usermine_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermine',
            name='inTournament',
            field=models.BooleanField(default=False),
        ),
    ]
