# Generated by Django 3.2.10 on 2024-01-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_usermine_intournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermine',
            name='inTournament',
            field=models.IntegerField(default=0),
        ),
    ]
