# Generated by Django 3.2.10 on 2024-01-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_usermine_intournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermine',
            name='tournament_id',
            field=models.CharField(default='', max_length=128),
        ),
    ]
