# Generated by Django 3.2.10 on 2024-01-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_usermine_intournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermine',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
