# Generated by Django 3.2.10 on 2024-01-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_usermine_email'),
        ('accounts', '0022_usermine_tournament_id'),
    ]

    operations = [
    ]
